### ISSUE TITLE
[Feat]: Provide hide check all prop to Dropdown

### ISSUE THREAD

**Issue by HaykAghajanyan** [softconstruct/gene-ui-components#141]
### Component

Dropdown

### Is your feature request related to a problem? Please describe.

Multiselect Dropdown has hideSelectAll prop which calculates from data count. It would be good if user can provide hideSelectAll prop to Dropdown and hide check all option

### Describe the solution you'd like

provide hideSelectAll prop to Dropdown and pass it to MultiSelect 

### Are you able to assist to bring the feature to reality?

yes

**Comment by GaroGabrielyan** [comment]
Hi @HaykAghajanyan ,

Thank you for your suggestion.

Could you please provide a detailed use case and reasoning for why this prop is necessary? Additionally, could you explain why the current default behavior does not meet your requirements?

**Comment by HaykAghajanyan** [comment]
Hi, @GaroGabrielyan .

The current version of the hideSelectAll prop does not provide the ability to manually hide the 'Select All' option. In our project, we have several dropdowns with multiselect that should not have the 'Select All' option.

**Comment by HaykAghajanyan** [comment]
Our design was changed for UX purposes, so the issue will be closed.
