### ISSUE TITLE
[Feat]: Move search field to opened Single-select dropdown

### ISSUE THREAD

**Issue by razzaramian** [softconstruct/gene-ui-components#211]
### Component

Dropdown (single-select)

### Describe the solution you'd like

Place the search field inside the opened single-select dropdown for consistency with the multi-select dropdown.

### Are you able to assist to bring the feature to reality?

no

**Comment by NarekArshakyan** [comment]
We are currently working on the new 3.0.0 version of the Gene UI design system, and as this is just an improvement, not a critical issue for the current version, we have decided to close this issue. Thanks for your understanding.

**Comment by NarekArshakyan** [comment]
We are currently working on the new 3.0.0 version of the Gene UI design system, and as this is just an improvement, not a critical issue for the current version, we have decided to close this issue. Thanks for your understanding.
