### ISSUE TITLE
[Bug]: Long text issue with back button being overlapped

### ISSUE THREAD

**Issue by meriminasyan** [softconstruct/gene-ui-components#41]
### Component

Profile

### Is this a regression?

None

### Describe the bug

When there is a long text as a title with the back button in the popover after clicking on the Profile, the text and the button are overlapped. 

### To Reproduce

1. give the Profile component the following data as an example :  
menuProps={{
          data: [{ title: 'issue with a long text as a title ', children: [{ title: 'text 2 for the child' }] }],
 }}

### Expected behavior

There should be enough space for both title and back button to be visible clearly, without any overlaps 

### Screenshots

![Capture](https://github.com/softconstruct/gene-ui-components/assets/153910406/e17166b5-2efc-4c2b-91bb-2647cc961dee)

### Package version

2.11.2

### Desktop

. OS: 
. Browser & version: 
. Additional Information:

### Smartphone

. Device:
. OS: 
. Browser & version: 
. Additional Information:

**Comment by meriminasyan** [comment]
would it be possible to have the content size?

**Comment by NarekArshakyan** [comment]
How do you see the solution?

**Comment by NarekArshakyan** [comment]
increasing the width or adding truncate ?

**Comment by meriminasyan** [comment]
maybe increasing the width with max width restriction?

**Comment by NarekArshakyan** [comment]
We negotiated as a team and decided to add truncate because changing the width would require a lot of changes. Thank you!
