### ISSUE TITLE
[Bug]: Widget Image Bug

### ISSUE THREAD

**Issue by SargisKarapetyan** [softconstruct/gene-ui-components#54]
### Component

Widget

### Is this a regression?

None

### Describe the bug

When using the widget component and not passing the `img` prop, `<li class="image"></li>` is still rendered and takes up space. Please remove `<li class="image"></li>` if the `img` prop is not passed.

### To Reproduce

Render the Widget component with the prop `type='default'` and without the `img` prop,

### Expected behavior

When using the Widget component with the prop `type='default'` and without the `img` prop, the `<li class="image"></li>` should not be rendered.

### Screenshots

![Screenshot from 2024-01-24 18-38-12](https://github.com/softconstruct/gene-ui-components/assets/45062872/11ad42a8-bd8c-47f9-aca6-91237d78f749)

### Package version

2.12.0

**Comment by hamikhambardzumyan** [comment]
Hi @SargisKarapetyan. Please refine what is your use case. Do you need the `Widget` component without an image?

**Comment by hamikhambardzumyan** [comment]
Using the `type` prop you can choose another `Widget` appearance where you can remove the `img` prop and get a more minimal widget UI.

https://github.com/softconstruct/gene-ui-components/assets/150047343/c9f068fa-df9d-460c-acdf-db2b1174d67f

**Comment by SargisKarapetyan** [comment]
I have to use the `default` type because the `headerActions` prop is only supported in the `default` type.

**Comment by hamikhambardzumyan** [comment]
Got it thx. We will add the new prop `withHeaderActions` which will cover the `compact` type case also.

**Comment by SargisKarapetyan** [comment]
Thanks for the update!
